apiVersion: v1
description: A policy-aware provider for OpenFaaS (Functions as a Service)
name: openfaas-federation
version: 0.1.0
sources:
- https://github.com/openfaas/faas
- https://github.com/openfaas/faas-netes
- https://github.com/PEng2020-Subject3/faas-policy-provider
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
- functions
- service
maintainers:
- name: alexellis
  email: alex@openfaas.com
